import React from 'react';
import ReactDOM from 'react-dom/client';
import { motion, MotionConfig } from 'motion/react';
import { ArrowUpRight, ArrowDown, ArrowRight, Plus, Menu, X } from 'lucide-react';
import { apps, profile, skills, upcoming } from './data';
import './style.css';

const asset = (path: string) => `${import.meta.env.BASE_URL}${path}`;
const nav = [['Work', '#work'], ['About', '#about'], ['Process', '#process'], ['Contact', '#contact']];
function Reveal({ children, className = '' }: { children: React.ReactNode; className?: string }) {
  return <motion.div className={className} initial={{ opacity: 0, y: 22 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .12 }} transition={{ duration: .65 }}>{children}</motion.div>;
}
function External({ href, children, className = '' }: { href: string; children: React.ReactNode; className?: string }) { return <a className={className} href={href} target="_blank" rel="noopener noreferrer">{children}<ArrowUpRight size={18} aria-hidden="true"/><span className="sr-only"> (opens in a new tab)</span></a>; }
function App() {
  const [menu, setMenu] = React.useState(false);
  return <MotionConfig reducedMotion="user"><a href="#main" className="skip-link">Skip to content</a>
    <header className="site-header wrap"><a href="#" className="wordmark" aria-label="Nishit Dave home">nishit dave</a><nav aria-label="Main navigation" className={menu ? 'open' : ''}>{nav.map(([name, href]) => <a key={name} href={href} onClick={() => setMenu(false)}>{name}</a>)}</nav><span className="header-note"><i/> Independent by design</span><button className="menu-button" aria-label={menu ? 'Close navigation' : 'Open navigation'} aria-expanded={menu} onClick={() => setMenu(!menu)}>{menu ? <X/> : <Menu/>}</button></header>
    <main id="main">
      <section className="hero wrap" aria-labelledby="hero-title"><div className="eyebrow hero-eyebrow"><span>Independent software developer & app builder</span><span>Ideas → useful things</span></div><Reveal><h1 id="hero-title">HEY, I’M<br/><span>NISHIT DAVE.</span><span className="hero-star" aria-hidden="true">✳</span></h1></Reveal><div className="hero-bottom"><div className="portrait"><img src={asset("nishit-avatar.png")} alt="Illustrated avatar of Nishit Dave" width="1280" height="1280" fetchPriority="high"/><span className="portrait-caption">Nishit Dave / Independent developer</span></div><Reveal className="hero-copy"><span className="eyebrow">Thoughtfully made. Independently built.</span><h2>Building apps and digital products<br/><em>since <time dateTime={profile.journeyStartDate}>28 March 2025</time>.</em></h2><p>I’m an independent developer designing, developing, and publishing applications that make everyday life a little simpler.</p><div className="hero-actions"><a href="#work" className="button">Explore my apps <ArrowDown size={17}/></a><a href="#contact" className="text-link">Contact me <ArrowUpRight size={17}/></a></div></Reveal></div><div className="hero-foot"><span>Mobile apps · AI-powered tools · Digital products</span><a href="#work">Scroll to explore <ArrowDown size={14}/></a></div></section>
      <section id="work" className="work wrap"><Reveal className="section-heading"><div><span className="eyebrow">01 / Selected apps</span><h2>Small ideas.<br/><em>Real-world products.</em></h2></div><p>A collection of apps I’ve independently built and published. Different problems, the same care for the details.</p></Reveal>
        {apps.map((app, index) => <Reveal className={`project ${index % 2 ? 'reverse' : ''}`} key={app.id}><div className="project-art" style={{ background: app.color }}><span className="art-label">{app.label}</span><div className="screens"><img className="screen secondary-screen" src={asset(app.screenshots[1])} alt={`${app.shortName} — official App Store screenshot 2`} loading="lazy" width="600" height="900"/><img className="screen primary-screen" src={asset(app.screenshots[0])} alt={`${app.shortName} — official App Store screenshot 1`} loading="lazy" width="600" height="900"/></div><span className="art-footer">Designed for iPhone <span>↗</span></span></div><div className="project-copy"><div className="project-top"><img src={asset(app.icon)} alt={`${app.shortName} app icon`} loading="lazy" width="64" height="64"/><span className="eyebrow">{String(index + 1).padStart(2, '0')} / {app.category}</span></div><h3>{app.name}</h3><div className="release-date">Published <time dateTime={app.releaseDate}>{new Intl.DateTimeFormat("en-GB", { day: "numeric", month: "long", year: "numeric", timeZone: "UTC" }).format(new Date(app.releaseDate))}</time></div><h4>{app.tagline}</h4><p>{app.description}</p><a href={app.url} className="app-store-badge" target="_blank" rel="noopener noreferrer"><img src={asset("app-store-badge.svg")} alt={`Download ${app.shortName} on the App Store`} width="1617" height="546" loading="lazy"/><span className="sr-only"> (opens in a new tab)</span></a></div></Reveal>)}
        <External href={profile.appStore} className="all-apps">Explore my App Store profile</External>
      </section>
      <section className="building wrap" id="building"><Reveal><div className="section-label"><span className="eyebrow">02 / On the workbench</span><span className="status"><i/> In development</span></div>{upcoming.map(project => <div className="building-grid" key={project.name}><div><h2>{project.name}<span>↗</span></h2><div className="release-date">Started <time dateTime={project.startDate}>{new Intl.DateTimeFormat("en-GB", { day: "numeric", month: "long", year: "numeric", timeZone: "UTC" }).format(new Date(project.startDate))}</time></div><p>{project.description}</p><External href={project.url} className="text-link">Visit Clipzer</External></div><div className="clipzer-art" aria-hidden="true"><div className="video-frame"><span className="play">▶</span><div className="timeline"><i/><i/><i/><i/><i/></div></div><div className="clip-frame"><span>▶</span></div><span className="clip-caption">One idea. New possibilities.</span></div></div>)}</Reveal></section>
      <section id="about" className="about wrap"><div className="eyebrow">03 / The person behind the products</div><Reveal className="about-grid"><h2>A builder at heart.<br/><em>Curious by nature.</em></h2><div><p className="lead">I’m Nishit, an independent developer who enjoys turning a useful idea into something people can actually use.</p><p>I began my solo development journey on <time dateTime={profile.journeyStartDate}>28 March 2025</time>. My work brings together product design, mobile development, AI integrations, and software launches. I build across health, fitness, productivity, education, and AI-powered tools.</p><p>I like practical problems, thoughtful interfaces, and the process of making things better. Research, experiment, ship, learn — then do it again.</p><span className="signature">Nishit Dave</span></div></Reveal><div className="skills"><span className="eyebrow">My toolkit</span><div>{skills.map(skill => <span key={skill}>{skill}<Plus size={14} aria-hidden="true"/></span>)}</div></div></section>
      <section id="process" className="process wrap"><Reveal className="section-heading"><div><span className="eyebrow">04 / How I work</span><h2>From a spark<br/><em>to something real.</em></h2></div><p>A simple process, with room to explore. Every stage is a chance to make the product more useful.</p></Reveal><div className="process-grid">{[['Idea & Research', 'Find a practical problem. Understand who it matters to.'], ['Design', 'Shape the experience. Make the essential feel effortless.'], ['Development', 'Build with care. Test the details and refine the product.'], ['Launch & Iterate', 'Publish, listen, and keep improving.']].map(([title, description], i) => <Reveal key={title}><div className="process-number">0{i + 1}<ArrowRight size={23} aria-hidden="true"/></div><h3>{title}</h3><p>{description}</p></Reveal>)}</div></section>
      <section id="contact" className="contact"><div className="wrap"><div className="contact-top"><span className="eyebrow">05 / Get in touch</span><span className="eyebrow">Good things start with a conversation.</span></div><Reveal><h2>LET’S BUILD<br/><em>SOMETHING.</em><ArrowUpRight aria-hidden="true"/></h2></Reveal><div className="contact-bottom">{profile.email ? <a className="email" href={`mailto:${profile.email}`}>{profile.email}<ArrowUpRight/></a> : <div className="email-placeholder"><span>Contact email coming soon</span><small>Custom-domain mailbox awaiting configuration.</small></div>}<div className="socials">{Object.entries(profile.socials).map(([name, url]) => url ? <External href={url} key={name}>{name}</External> : <span key={name}>{name}<small>Not configured</small></span>)}<External href={profile.appStore}>App Store</External></div></div></div></section>
    </main><footer className="wrap"><a href="#" className="wordmark">nishit dave</a><span>© {new Date().getFullYear()} Nishit Dave</span><nav aria-label="Footer navigation">{nav.map(([name, href]) => <a key={name} href={href}>{name}</a>)}</nav>{Object.entries(profile.socials).map(([name, url]) => url ? <External href={url} key={name}>{name}</External> : null)}<External href={profile.appStore}>App Store</External><a href="#main" className="back-top">Back to top ↑</a></footer>
  </MotionConfig>;
}
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);











